# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_1_0_FULL.zip?_ga=2.47462311.1493357375.1597372715-269570672.1596526126'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_1_0_FULL.zip?_ga=2.47462311.1493357375.1597372715-269570672.1596526126'
  WindowsRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows_v3_1_0_FULL.zip?_ga=2.54261672.1493357375.1597372715-269570672.1596526126'

jobs:
- template: 'OpenLive-Android/open-live-template.yml'
  parameters:
    project: 'OpenLive-Android'
    name: 'OpenLive_Android'

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSSwiftOpenLive'
    workingDirectory: 'OpenLive-iOS'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'iOSOCOpenLive'
    workingDirectory: 'OpenLive-iOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(iOSRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacSwiftOpenLive'
    workingDirectory: 'OpenLive-macOS'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

- template: cicd/templates/build-mac.yml
  parameters:
    displayName: 'MacOCOpenLive'
    workingDirectory: 'OpenLive-macOS-Objective-C'
    scheme: 'OpenLive'
    sdkurl: $(MacRTCSDK)

#Windows MFC demo
- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'WindowsOpenLiveMFC'
    workingDirectory: 'OpenLive-Windows-MFC'
    scheme: 'OpenLive-Windows-MFC'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    Machine: 'win32'
    architecture: 'x86'
    ReleasePath: 'Release'

- template: cicd/templates/build-Windows.yml
  parameters:
    displayName: 'WindowsOpenLiveMFC64'
    workingDirectory: 'OpenLive-Windows-MFC'
    scheme: 'OpenLive-Windows-MFC'
    sdkurl: $(WindowsRTCSDK)
    solutionName: 'OpenLive.sln'
    Machine: 'x64'
    architecture: 'x64'
    ReleasePath: 'x64/Release'
#Windows QT
- template: cicd/templates/build-Windows-qt.yml
  parameters:
    displayName: 'WindowsOpenLive'
    workingDirectory: 'OpenLive-Windows'
    scheme: 'OpenLive-Windows'
    sdkurl: $(WindowsRTCSDK)
    architecture: 'x86'
    ReleasePath: 'Release'
- template: cicd/templates/build-Windows-qt.yml
  parameters:
    displayName: 'WindowsOpenLive64'
    workingDirectory: 'OpenLive-Windows'
    scheme: 'OpenLive-Windows'
    sdkurl: $(WindowsRTCSDK)
    architecture: 'x64'
    ReleasePath: 'Release'